### ISSUE TITLE
how to run it locally?

### ISSUE THREAD

**Issue by lw19901** [xarvh/herzog-drei#53]
I downloaded this ,extracted it, and ran elm reactor in the directory. Then I tried to open MainScene.elm, App.elm, and many other .elm files and keep getting this message in the browser

"Initialization Error
ReferenceError: _Platform_export is not defined"

Sorry I'm new to elm, trying to use this game as a way to jumpstart my understanding

**Comment by xarvh** [comment]
Unfortunately `elm reactor` is extremely limited in what it can run: for example it can't deal with elm ports, which makes it useless for any non-trivial usage.

The way to run the game is to run `make` from within the directory, then open `index.html` with your browser.

Let me know if you encounter problems!

**Comment by lw19901** [comment]
It still doesn't work for some reason. Running elm make Main.elm it says 

```
Success, compiled 1 module. Main ---> index.html
```
but opening index.html displays error 

```
Initialization Error
Error: Problem with the flags given to your Elm program on initialization.

Problem with the given value:

undefined

Expecting an OBJECT with a field named windowWidth

**Comment by xarvh** [comment]
You ran `elm make` instead of `make` ^_^

This means that elm overwrote `index.html`.

If you don't have `make`, you need to run `elm make Main.elm --output build/app.js`

**Comment by xarvh** [comment]
Oh, and restore the original `index.html` otherwise it won't run.

**Comment by lw19901** [comment]
elm make Main.elm --output build/app.js was the special command that made a fresh clone work
however I didn't have to run make by itself (it did nothing besides say make is not a recognized as an internal or external command, operable program or batch file)

opening index.html after elm make Main.elm --output build/app.js just works, thank you!
